//
// Created by xflajs00 on 28.10.2021.
//

#ifndef PF_GLFW_ENUMS_GAMEPADBUTTON_H
#define PF_GLFW_ENUMS_GAMEPADBUTTON_H

#include <GLFW/glfw3.h>
#include <pf_glfw/_export.h>

namespace pf::glfw {
enum class PF_GLFW_EXPORT GamepadButton {
  A = GLFW_GAMEPAD_BUTTON_A,
  B = GLFW_GAMEPAD_BUTTON_B,
  X = GLFW_GAMEPAD_BUTTON_X,
  Y = GLFW_GAMEPAD_BUTTON_Y,
  LeftBumper = GLFW_GAMEPAD_BUTTON_LEFT_BUMPER,
  RightBumper = GLFW_GAMEPAD_BUTTON_RIGHT_BUMPER,
  Back = GLFW_GAMEPAD_BUTTON_BACK,
  Start = GLFW_GAMEPAD_BUTTON_START,
  Guide = GLFW_GAMEPAD_BUTTON_GUIDE,
  LeftThumb = GLFW_GAMEPAD_BUTTON_LEFT_THUMB,
  RightThumb = GLFW_GAMEPAD_BUTTON_RIGHT_THUMB,
  DpadUp = GLFW_GAMEPAD_BUTTON_DPAD_UP,
  DpadRight = GLFW_GAMEPAD_BUTTON_DPAD_RIGHT,
  DpadDown = GLFW_GAMEPAD_BUTTON_DPAD_DOWN,
  DpadLeft = GLFW_GAMEPAD_BUTTON_DPAD_LEFT,
  Last = GLFW_GAMEPAD_BUTTON_LAST,
  Cross = GLFW_GAMEPAD_BUTTON_CROSS,
  Circle = GLFW_GAMEPAD_BUTTON_CIRCLE,
  Square = GLFW_GAMEPAD_BUTTON_SQUARE,
  Triangle = GLFW_GAMEPAD_BUTTON_TRIANGLE,
};
}
#endif//PF_GLFW_ENUMS_GAMEPADBUTTON_H
